name: Deploy Microservice to Minikube (via ngrok)

on:
  repository_dispatch:
    types: [deploy-microservice]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig (Windows PowerShell)
        shell: powershell
        run: |
          $base64Encoded = @"
          ${{ secrets.KUBE_CONFIG_DATA }}
          "@
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($base64Encoded)) | Out-File -FilePath kubeconfig -Encoding ascii
          $env:KUBECONFIG = "$PWD\kubeconfig"
          kubectl get nodes

      # - name: Setup Helm
      #   uses: azure/setup-helm@v4

      - name: Add bitnami charts with Helm
        shell: powershell
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
      - name: Deploy mysql with Helm
        shell: powershell
        run: |
          helm upgrade mysql ./k8s-helm/mysql-chart `
            --install `
            --namespace my-apps `
            --create-namespace `
            --atomic
      - name: Deploy redis with Helm
        shell: powershell
        run: |
          helm upgrade redis ./k8s-helm/redis-chart `
                --install `
                --namespace my-apps `
                --atomic

      - name: Deploy my services with Helm
        shell: powershell
        run: |
      - name: Deploy Service with Helm
        shell: powershell
        run: |
          $SERVICE = "${{ github.event.client_payload.service }}"
          $TAG = "${{ github.event.client_payload.tag }}"

          Write-Host "Deploying service: $SERVICE with image tag: $TAG"

          helm upgrade $SERVICE ./k8s-helm/services-charts/$SERVICE `
            --install `
            --namespace my-apps `
            --create-namespace `
            --set "image.repository=docker.io/mohamedfawzi/$SERVICE" `
            --set "image.tag=$TAG" `
            --atomic
